name: package

on:
  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.1

      - name: Run a multi-line script
        run: |
          ls
          mvn package
